#!/bin/sh

cwd=$PWD

url_kernel="http://download.tizen.org/snapshots/tizen/common/latest/images/emulator32-wayland/common-emulator-wayland-mbr-i586/tizen-common_20141020.2_common-emulator-wayland-mbr-i586-vmlinuz-3.12.18-2.3-common-i386-emulator"

url_rootfs="http://download.tizen.org/snapshots/tizen/common/latest/images/emulator32-wayland/common-emulator-wayland-mbr-i586/tizen-common_20141020.2_common-emulator-wayland-mbr-i586.tar.gz"

rootfs_tgz="tizen-common_20141020.2_common-emulator-wayland-mbr-i586.tar.gz"
size=1G
rootfs="tizen-common.img"
kernel="tizen-common_20141020.2_common-emulator-wayland-mbr-i586-vmlinuz-3.12.18-2.3-common-i386-emulator"
swap="swap.x86"

cmdline='console=ttyS0 root=/dev/sda rw video=LVDS-1:1920x1080-32@60 ip=10.0.2.15::10.0.2.2:255.255.255.0::eth0:none'
cmdline="$cmdline vm_name=tizen sdb_port=26100"

serial="file://dev/stderr"

if [ ! -f  $rootfs_tgz ]; then
   wget $url_rootfs
fi

if [ ! -f  $rootfs ]; then
   tar xf $rootfs_tgz
fi

if [ ! -f  $kernel ]; then
   wget $url_kernel
fi

if [ ! -f  $swap ]; then
  qemu-img create -f raw $swap 1G
  mkswap $swap
fi

qemu-system-i386 \
    -M pc \
    -m 1024 \
    -drive file="$rootfs",if=virtio,index=1 \
    -drive file="$swap",if=virtio,index=2 \
    -boot c \
    -append "$cmdline" \
    -serial "$serial" \
    -kernel "$kernel" \
    -enable-kvm -smp 2 -vga none -display sdl -soundhw all \
    -vigs-backend gl -yagl-backend vigs -enable-vigs -enable-yagl \
    -usb -device usb-mouse -device usb-kbd \
    -net nic -net user -redir tcp:22122::22  \
   #eol

